Repository securesign/cosign, pull requests merged in 2023-10, with the labels that each got.

#17 :robot: triggering CI on branch 'redhat-v2.1.1' after synching from upstream/v2.1.1
  ci
  redhat/release/update-to-head.sh
Labels: kind/sync-fork-to-upstream, approved

#37 SECURESIGN-115 | Add new label to dockerfiles for Comet
  redhat/overlays/Dockerfile
Labels: approved, lgtm

#39 chore: modify update script to avoid merge conflicts
  redhat/release/update-to-head.sh
Labels: approved, lgtm

#26 :robot: triggering CI on branch 'redhat-v2.2.0' after synching from upstream/v2.2.0
  .github/workflows/tests.yaml
  Dockerfile
  OWNERS
  ci
  redhat/patches/0001-tests-yaml.patch
  redhat/release/update-to-head.sh
Labels: kind/sync-fork-to-upstream, do-not-merge/invalid-owners-file

#42 :robot: triggering CI on branch 'redhat-v2.2.0' after synching from upstream/v2.2.0
  Dockerfile
  ci
  redhat/overlays/.github/workflows/tests.yaml
  redhat/release/update-to-head.sh
Labels: kind/sync-fork-to-upstream, approved

#46 chore: enable hermetic builds and prefetched dependencies
  .tekton/cosign-pull-request.yaml
  .tekton/cosign-push.yaml
Labels: approved, lgtm

#45 update script, convert patch to overlay
  redhat/overlays/.github/workflows/tests.yaml
  redhat/patches/0001-tests-yaml.patch
  redhat/release/update-to-head.sh
Labels: lgtm

#50 deps(ubi-minimal): bump to latest sha256
  redhat/overlays/Dockerfile
Labels: approved, lgtm

#52 :robot: triggering CI on branch 'redhat-v2.1.1' after synching from upstream/v2.1.1
  Dockerfile
  ci
  redhat/overlays/Dockerfile
Labels: kind/sync-fork-to-upstream, approved

#54 Adding multiarch to the dockerfile
  redhat/overlays/Dockerfile
Labels: approved, lgtm

#56 :robot: triggering CI on branch 'redhat-v2.1.1' after synching from upstream/v2.1.1
  Dockerfile
  ci
  redhat/overlays/Dockerfile
Labels: kind/sync-fork-to-upstream, approved

#57 feat: Add GH action
  .github/workflows/cronjobs.yaml
Labels: approved, lgtm

#62 Renamed linux cosign binary to be just "cosign".
  redhat/overlays/Dockerfile
Labels: lgtm

#64 :robot: triggering CI on branch 'redhat-v2.1.1' after synching from upstream/v2.1.1
  Dockerfile
  ci
  redhat/overlays/Dockerfile
Labels: kind/sync-fork-to-upstream

#65 :robot: triggering CI on branch 'redhat-v2.1.1' after synching from upstream/v2.1.1
  Dockerfile
  ci
  redhat/overlays/Dockerfile
Labels: kind/sync-fork-to-upstream, approved

#71 Specifying build targets
  redhat/overlays/Dockerfile
Labels: lgtm

#73 :robot: triggering CI on branch 'redhat-v2.1.1' after synching from upstream/v2.1.1
  Build.mak
  Dockerfile
  ci
  redhat/overlays/Build.mak
  redhat/overlays/Dockerfile
Labels: kind/sync-fork-to-upstream, approved, lgtm
