Repository securesign/cosign, pull requests merged in 2023-09, with the labels that each got.

#5 chore: move overlays to root in sync script
  redhat/overlays/Dockerfile
  redhat/release/update-to-head.sh
Labels: approved, lgtm

#2 :robot: triggering CI on branch 'redhat-v2.1.1' after synching from upstream/v2.1.1
  ci
Labels: kind/sync-fork-to-upstream, approved

#10 add patch file for validate-release job
  redhat/patches/0002-validate-release-patch.txt
Labels: approved, lgtm, ok-to-test

#8 Changes needed for rhtap support
  redhat/release/update-to-head.sh
Labels: approved, lgtm

#14 Adds labels to conform to RH enterprise contract
  redhat/overlays/Dockerfile
Labels: approved, lgtm

#19 Move Dockerfile labels to the run image
  redhat/overlays/Dockerfile
Labels: approved, lgtm

#23 chore: don't force push the release branch
  redhat/release/update-to-head.sh
Labels: approved, lgtm

#25 remove validate-release.patch
  redhat/patches/0002-validate-release-patch.txt
Labels: approved, lgtm

#22 Modify RHTAP pipeline default for hermetic builds
  .tekton/cosign-pull-request.yaml
  .tekton/cosign-push.yaml
Labels: approved
