Repository securesign/cosign, pull requests merged in 2023-11, with the labels that each got.

#78 rhtap: update Dockerfile to get a clean git hash
  redhat/overlays/Dockerfile
Labels: approved

#81 :robot: triggering CI on branch 'redhat-v2.1.1' after synching from upstream/v2.1.1
  Dockerfile
  ci
  redhat/overlays/Dockerfile
Labels: kind/sync-fork-to-upstream, approved

#82 Cosign source image
  .tekton/cosign-pull-request.yaml
  .tekton/cosign-push.yaml
Labels: approved, lgtm

#94 [SECURESIGN-247] Adding necessary files for build and RHTAP Onboarding
  Build.mak
  Dockerfile
Labels: lgtm

#96 [SECURESIGN-252] | Enabling build-source-image for cli.
  .tekton/cosign-cli-2-2-pull-request.yaml
  .tekton/cosign-cli-2-2-push.yaml
Labels: lgtm
